server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/editor?serverTimezone=GMT
    username: root
    password: 134679
  security:
    user:
      name: user
      password: 123
